spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:musinsa-db
    username: sa

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      encoding: utf-8
      mode: always
      data-locations: classpath:db/data.sql
  data:
    redis:
      host: localhost
      port: 6370

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.musinsa.assignment: debug

